// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: drive_to_point.proto

package pl.edu.agh.amber.drivetopoint.proto;

public final class DriveToPointProto {
  private DriveToPointProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.setTargets);
    registry.add(pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.getNextTarget);
    registry.add(pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.getNextTargets);
    registry.add(pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.getVisitedTarget);
    registry.add(pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.getVisitedTargets);
    registry.add(pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.targets);
    registry.add(pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.location);
    registry.add(pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.getConfiguration);
    registry.add(pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.configuration);
  }
  public interface TargetsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated double longitudes = 1 [packed = true];
    /**
     * <code>repeated double longitudes = 1 [packed = true];</code>
     */
    java.util.List<java.lang.Double> getLongitudesList();
    /**
     * <code>repeated double longitudes = 1 [packed = true];</code>
     */
    int getLongitudesCount();
    /**
     * <code>repeated double longitudes = 1 [packed = true];</code>
     */
    double getLongitudes(int index);

    // repeated double latitudes = 2 [packed = true];
    /**
     * <code>repeated double latitudes = 2 [packed = true];</code>
     */
    java.util.List<java.lang.Double> getLatitudesList();
    /**
     * <code>repeated double latitudes = 2 [packed = true];</code>
     */
    int getLatitudesCount();
    /**
     * <code>repeated double latitudes = 2 [packed = true];</code>
     */
    double getLatitudes(int index);

    // repeated double radiuses = 3 [packed = true];
    /**
     * <code>repeated double radiuses = 3 [packed = true];</code>
     */
    java.util.List<java.lang.Double> getRadiusesList();
    /**
     * <code>repeated double radiuses = 3 [packed = true];</code>
     */
    int getRadiusesCount();
    /**
     * <code>repeated double radiuses = 3 [packed = true];</code>
     */
    double getRadiuses(int index);
  }
  /**
   * Protobuf type {@code amber.drive_to_point_proto.Targets}
   */
  public static final class Targets extends
      com.google.protobuf.GeneratedMessage
      implements TargetsOrBuilder {
    // Use Targets.newBuilder() to construct.
    private Targets(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Targets(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Targets defaultInstance;
    public static Targets getDefaultInstance() {
      return defaultInstance;
    }

    public Targets getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Targets(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                longitudes_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              longitudes_.add(input.readDouble());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                longitudes_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                longitudes_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 17: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                latitudes_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000002;
              }
              latitudes_.add(input.readDouble());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                latitudes_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                latitudes_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 25: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                radiuses_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000004;
              }
              radiuses_.add(input.readDouble());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                radiuses_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                radiuses_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          longitudes_ = java.util.Collections.unmodifiableList(longitudes_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          latitudes_ = java.util.Collections.unmodifiableList(latitudes_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          radiuses_ = java.util.Collections.unmodifiableList(radiuses_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.internal_static_amber_drive_to_point_proto_Targets_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.internal_static_amber_drive_to_point_proto_Targets_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets.class, pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets.Builder.class);
    }

    public static com.google.protobuf.Parser<Targets> PARSER =
        new com.google.protobuf.AbstractParser<Targets>() {
      public Targets parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Targets(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Targets> getParserForType() {
      return PARSER;
    }

    // repeated double longitudes = 1 [packed = true];
    public static final int LONGITUDES_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Double> longitudes_;
    /**
     * <code>repeated double longitudes = 1 [packed = true];</code>
     */
    public java.util.List<java.lang.Double>
        getLongitudesList() {
      return longitudes_;
    }
    /**
     * <code>repeated double longitudes = 1 [packed = true];</code>
     */
    public int getLongitudesCount() {
      return longitudes_.size();
    }
    /**
     * <code>repeated double longitudes = 1 [packed = true];</code>
     */
    public double getLongitudes(int index) {
      return longitudes_.get(index);
    }
    private int longitudesMemoizedSerializedSize = -1;

    // repeated double latitudes = 2 [packed = true];
    public static final int LATITUDES_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Double> latitudes_;
    /**
     * <code>repeated double latitudes = 2 [packed = true];</code>
     */
    public java.util.List<java.lang.Double>
        getLatitudesList() {
      return latitudes_;
    }
    /**
     * <code>repeated double latitudes = 2 [packed = true];</code>
     */
    public int getLatitudesCount() {
      return latitudes_.size();
    }
    /**
     * <code>repeated double latitudes = 2 [packed = true];</code>
     */
    public double getLatitudes(int index) {
      return latitudes_.get(index);
    }
    private int latitudesMemoizedSerializedSize = -1;

    // repeated double radiuses = 3 [packed = true];
    public static final int RADIUSES_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Double> radiuses_;
    /**
     * <code>repeated double radiuses = 3 [packed = true];</code>
     */
    public java.util.List<java.lang.Double>
        getRadiusesList() {
      return radiuses_;
    }
    /**
     * <code>repeated double radiuses = 3 [packed = true];</code>
     */
    public int getRadiusesCount() {
      return radiuses_.size();
    }
    /**
     * <code>repeated double radiuses = 3 [packed = true];</code>
     */
    public double getRadiuses(int index) {
      return radiuses_.get(index);
    }
    private int radiusesMemoizedSerializedSize = -1;

    private void initFields() {
      longitudes_ = java.util.Collections.emptyList();
      latitudes_ = java.util.Collections.emptyList();
      radiuses_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getLongitudesList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(longitudesMemoizedSerializedSize);
      }
      for (int i = 0; i < longitudes_.size(); i++) {
        output.writeDoubleNoTag(longitudes_.get(i));
      }
      if (getLatitudesList().size() > 0) {
        output.writeRawVarint32(18);
        output.writeRawVarint32(latitudesMemoizedSerializedSize);
      }
      for (int i = 0; i < latitudes_.size(); i++) {
        output.writeDoubleNoTag(latitudes_.get(i));
      }
      if (getRadiusesList().size() > 0) {
        output.writeRawVarint32(26);
        output.writeRawVarint32(radiusesMemoizedSerializedSize);
      }
      for (int i = 0; i < radiuses_.size(); i++) {
        output.writeDoubleNoTag(radiuses_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 8 * getLongitudesList().size();
        size += dataSize;
        if (!getLongitudesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        longitudesMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 8 * getLatitudesList().size();
        size += dataSize;
        if (!getLatitudesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        latitudesMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 8 * getRadiusesList().size();
        size += dataSize;
        if (!getRadiusesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        radiusesMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code amber.drive_to_point_proto.Targets}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.TargetsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.internal_static_amber_drive_to_point_proto_Targets_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.internal_static_amber_drive_to_point_proto_Targets_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets.class, pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets.Builder.class);
      }

      // Construct using pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        longitudes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        latitudes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        radiuses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.internal_static_amber_drive_to_point_proto_Targets_descriptor;
      }

      public pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets getDefaultInstanceForType() {
        return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets.getDefaultInstance();
      }

      public pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets build() {
        pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets buildPartial() {
        pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets result = new pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          longitudes_ = java.util.Collections.unmodifiableList(longitudes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.longitudes_ = longitudes_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          latitudes_ = java.util.Collections.unmodifiableList(latitudes_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.latitudes_ = latitudes_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          radiuses_ = java.util.Collections.unmodifiableList(radiuses_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.radiuses_ = radiuses_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets) {
          return mergeFrom((pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets other) {
        if (other == pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets.getDefaultInstance()) return this;
        if (!other.longitudes_.isEmpty()) {
          if (longitudes_.isEmpty()) {
            longitudes_ = other.longitudes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLongitudesIsMutable();
            longitudes_.addAll(other.longitudes_);
          }
          onChanged();
        }
        if (!other.latitudes_.isEmpty()) {
          if (latitudes_.isEmpty()) {
            latitudes_ = other.latitudes_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureLatitudesIsMutable();
            latitudes_.addAll(other.latitudes_);
          }
          onChanged();
        }
        if (!other.radiuses_.isEmpty()) {
          if (radiuses_.isEmpty()) {
            radiuses_ = other.radiuses_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureRadiusesIsMutable();
            radiuses_.addAll(other.radiuses_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated double longitudes = 1 [packed = true];
      private java.util.List<java.lang.Double> longitudes_ = java.util.Collections.emptyList();
      private void ensureLongitudesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          longitudes_ = new java.util.ArrayList<java.lang.Double>(longitudes_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated double longitudes = 1 [packed = true];</code>
       */
      public java.util.List<java.lang.Double>
          getLongitudesList() {
        return java.util.Collections.unmodifiableList(longitudes_);
      }
      /**
       * <code>repeated double longitudes = 1 [packed = true];</code>
       */
      public int getLongitudesCount() {
        return longitudes_.size();
      }
      /**
       * <code>repeated double longitudes = 1 [packed = true];</code>
       */
      public double getLongitudes(int index) {
        return longitudes_.get(index);
      }
      /**
       * <code>repeated double longitudes = 1 [packed = true];</code>
       */
      public Builder setLongitudes(
          int index, double value) {
        ensureLongitudesIsMutable();
        longitudes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double longitudes = 1 [packed = true];</code>
       */
      public Builder addLongitudes(double value) {
        ensureLongitudesIsMutable();
        longitudes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double longitudes = 1 [packed = true];</code>
       */
      public Builder addAllLongitudes(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureLongitudesIsMutable();
        super.addAll(values, longitudes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double longitudes = 1 [packed = true];</code>
       */
      public Builder clearLongitudes() {
        longitudes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // repeated double latitudes = 2 [packed = true];
      private java.util.List<java.lang.Double> latitudes_ = java.util.Collections.emptyList();
      private void ensureLatitudesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          latitudes_ = new java.util.ArrayList<java.lang.Double>(latitudes_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated double latitudes = 2 [packed = true];</code>
       */
      public java.util.List<java.lang.Double>
          getLatitudesList() {
        return java.util.Collections.unmodifiableList(latitudes_);
      }
      /**
       * <code>repeated double latitudes = 2 [packed = true];</code>
       */
      public int getLatitudesCount() {
        return latitudes_.size();
      }
      /**
       * <code>repeated double latitudes = 2 [packed = true];</code>
       */
      public double getLatitudes(int index) {
        return latitudes_.get(index);
      }
      /**
       * <code>repeated double latitudes = 2 [packed = true];</code>
       */
      public Builder setLatitudes(
          int index, double value) {
        ensureLatitudesIsMutable();
        latitudes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double latitudes = 2 [packed = true];</code>
       */
      public Builder addLatitudes(double value) {
        ensureLatitudesIsMutable();
        latitudes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double latitudes = 2 [packed = true];</code>
       */
      public Builder addAllLatitudes(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureLatitudesIsMutable();
        super.addAll(values, latitudes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double latitudes = 2 [packed = true];</code>
       */
      public Builder clearLatitudes() {
        latitudes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // repeated double radiuses = 3 [packed = true];
      private java.util.List<java.lang.Double> radiuses_ = java.util.Collections.emptyList();
      private void ensureRadiusesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          radiuses_ = new java.util.ArrayList<java.lang.Double>(radiuses_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated double radiuses = 3 [packed = true];</code>
       */
      public java.util.List<java.lang.Double>
          getRadiusesList() {
        return java.util.Collections.unmodifiableList(radiuses_);
      }
      /**
       * <code>repeated double radiuses = 3 [packed = true];</code>
       */
      public int getRadiusesCount() {
        return radiuses_.size();
      }
      /**
       * <code>repeated double radiuses = 3 [packed = true];</code>
       */
      public double getRadiuses(int index) {
        return radiuses_.get(index);
      }
      /**
       * <code>repeated double radiuses = 3 [packed = true];</code>
       */
      public Builder setRadiuses(
          int index, double value) {
        ensureRadiusesIsMutable();
        radiuses_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double radiuses = 3 [packed = true];</code>
       */
      public Builder addRadiuses(double value) {
        ensureRadiusesIsMutable();
        radiuses_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double radiuses = 3 [packed = true];</code>
       */
      public Builder addAllRadiuses(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureRadiusesIsMutable();
        super.addAll(values, radiuses_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double radiuses = 3 [packed = true];</code>
       */
      public Builder clearRadiuses() {
        radiuses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:amber.drive_to_point_proto.Targets)
    }

    static {
      defaultInstance = new Targets(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:amber.drive_to_point_proto.Targets)
  }

  public interface LocationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional double x = 1;
    /**
     * <code>optional double x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>optional double x = 1;</code>
     */
    double getX();

    // optional double y = 2;
    /**
     * <code>optional double y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>optional double y = 2;</code>
     */
    double getY();

    // optional double p = 3;
    /**
     * <code>optional double p = 3;</code>
     */
    boolean hasP();
    /**
     * <code>optional double p = 3;</code>
     */
    double getP();

    // optional double alfa = 4;
    /**
     * <code>optional double alfa = 4;</code>
     */
    boolean hasAlfa();
    /**
     * <code>optional double alfa = 4;</code>
     */
    double getAlfa();

    // optional int64 timeStamp = 5;
    /**
     * <code>optional int64 timeStamp = 5;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>optional int64 timeStamp = 5;</code>
     */
    long getTimeStamp();
  }
  /**
   * Protobuf type {@code amber.drive_to_point_proto.Location}
   */
  public static final class Location extends
      com.google.protobuf.GeneratedMessage
      implements LocationOrBuilder {
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Location(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Location defaultInstance;
    public static Location getDefaultInstance() {
      return defaultInstance;
    }

    public Location getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              x_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              y_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              p_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              alfa_ = input.readDouble();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timeStamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.internal_static_amber_drive_to_point_proto_Location_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.internal_static_amber_drive_to_point_proto_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location.class, pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location.Builder.class);
    }

    public static com.google.protobuf.Parser<Location> PARSER =
        new com.google.protobuf.AbstractParser<Location>() {
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Location(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional double x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private double x_;
    /**
     * <code>optional double x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double x = 1;</code>
     */
    public double getX() {
      return x_;
    }

    // optional double y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private double y_;
    /**
     * <code>optional double y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double y = 2;</code>
     */
    public double getY() {
      return y_;
    }

    // optional double p = 3;
    public static final int P_FIELD_NUMBER = 3;
    private double p_;
    /**
     * <code>optional double p = 3;</code>
     */
    public boolean hasP() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double p = 3;</code>
     */
    public double getP() {
      return p_;
    }

    // optional double alfa = 4;
    public static final int ALFA_FIELD_NUMBER = 4;
    private double alfa_;
    /**
     * <code>optional double alfa = 4;</code>
     */
    public boolean hasAlfa() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double alfa = 4;</code>
     */
    public double getAlfa() {
      return alfa_;
    }

    // optional int64 timeStamp = 5;
    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timeStamp_;
    /**
     * <code>optional int64 timeStamp = 5;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 timeStamp = 5;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    private void initFields() {
      x_ = 0D;
      y_ = 0D;
      p_ = 0D;
      alfa_ = 0D;
      timeStamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, p_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, alfa_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, timeStamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, p_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, alfa_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timeStamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code amber.drive_to_point_proto.Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.internal_static_amber_drive_to_point_proto_Location_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.internal_static_amber_drive_to_point_proto_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location.class, pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location.Builder.class);
      }

      // Construct using pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        p_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        alfa_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        timeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.internal_static_amber_drive_to_point_proto_Location_descriptor;
      }

      public pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location getDefaultInstanceForType() {
        return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location.getDefaultInstance();
      }

      public pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location build() {
        pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location buildPartial() {
        pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location result = new pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.p_ = p_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.alfa_ = alfa_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timeStamp_ = timeStamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location) {
          return mergeFrom((pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location other) {
        if (other == pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasP()) {
          setP(other.getP());
        }
        if (other.hasAlfa()) {
          setAlfa(other.getAlfa());
        }
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional double x = 1;
      private double x_ ;
      /**
       * <code>optional double x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double x = 1;</code>
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>optional double x = 1;</code>
       */
      public Builder setX(double value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        onChanged();
        return this;
      }

      // optional double y = 2;
      private double y_ ;
      /**
       * <code>optional double y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double y = 2;</code>
       */
      public double getY() {
        return y_;
      }
      /**
       * <code>optional double y = 2;</code>
       */
      public Builder setY(double value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        onChanged();
        return this;
      }

      // optional double p = 3;
      private double p_ ;
      /**
       * <code>optional double p = 3;</code>
       */
      public boolean hasP() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double p = 3;</code>
       */
      public double getP() {
        return p_;
      }
      /**
       * <code>optional double p = 3;</code>
       */
      public Builder setP(double value) {
        bitField0_ |= 0x00000004;
        p_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double p = 3;</code>
       */
      public Builder clearP() {
        bitField0_ = (bitField0_ & ~0x00000004);
        p_ = 0D;
        onChanged();
        return this;
      }

      // optional double alfa = 4;
      private double alfa_ ;
      /**
       * <code>optional double alfa = 4;</code>
       */
      public boolean hasAlfa() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double alfa = 4;</code>
       */
      public double getAlfa() {
        return alfa_;
      }
      /**
       * <code>optional double alfa = 4;</code>
       */
      public Builder setAlfa(double value) {
        bitField0_ |= 0x00000008;
        alfa_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double alfa = 4;</code>
       */
      public Builder clearAlfa() {
        bitField0_ = (bitField0_ & ~0x00000008);
        alfa_ = 0D;
        onChanged();
        return this;
      }

      // optional int64 timeStamp = 5;
      private long timeStamp_ ;
      /**
       * <code>optional int64 timeStamp = 5;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 timeStamp = 5;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>optional int64 timeStamp = 5;</code>
       */
      public Builder setTimeStamp(long value) {
        bitField0_ |= 0x00000010;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timeStamp = 5;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:amber.drive_to_point_proto.Location)
    }

    static {
      defaultInstance = new Location(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:amber.drive_to_point_proto.Location)
  }

  public interface ConfigurationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional double maxSpeed = 1;
    /**
     * <code>optional double maxSpeed = 1;</code>
     */
    boolean hasMaxSpeed();
    /**
     * <code>optional double maxSpeed = 1;</code>
     */
    double getMaxSpeed();
  }
  /**
   * Protobuf type {@code amber.drive_to_point_proto.Configuration}
   */
  public static final class Configuration extends
      com.google.protobuf.GeneratedMessage
      implements ConfigurationOrBuilder {
    // Use Configuration.newBuilder() to construct.
    private Configuration(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Configuration(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Configuration defaultInstance;
    public static Configuration getDefaultInstance() {
      return defaultInstance;
    }

    public Configuration getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Configuration(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              maxSpeed_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.internal_static_amber_drive_to_point_proto_Configuration_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.internal_static_amber_drive_to_point_proto_Configuration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration.class, pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration.Builder.class);
    }

    public static com.google.protobuf.Parser<Configuration> PARSER =
        new com.google.protobuf.AbstractParser<Configuration>() {
      public Configuration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Configuration(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Configuration> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional double maxSpeed = 1;
    public static final int MAXSPEED_FIELD_NUMBER = 1;
    private double maxSpeed_;
    /**
     * <code>optional double maxSpeed = 1;</code>
     */
    public boolean hasMaxSpeed() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double maxSpeed = 1;</code>
     */
    public double getMaxSpeed() {
      return maxSpeed_;
    }

    private void initFields() {
      maxSpeed_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, maxSpeed_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, maxSpeed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code amber.drive_to_point_proto.Configuration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.ConfigurationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.internal_static_amber_drive_to_point_proto_Configuration_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.internal_static_amber_drive_to_point_proto_Configuration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration.class, pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration.Builder.class);
      }

      // Construct using pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        maxSpeed_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.internal_static_amber_drive_to_point_proto_Configuration_descriptor;
      }

      public pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration getDefaultInstanceForType() {
        return pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration.getDefaultInstance();
      }

      public pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration build() {
        pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration buildPartial() {
        pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration result = new pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.maxSpeed_ = maxSpeed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration) {
          return mergeFrom((pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration other) {
        if (other == pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration.getDefaultInstance()) return this;
        if (other.hasMaxSpeed()) {
          setMaxSpeed(other.getMaxSpeed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional double maxSpeed = 1;
      private double maxSpeed_ ;
      /**
       * <code>optional double maxSpeed = 1;</code>
       */
      public boolean hasMaxSpeed() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double maxSpeed = 1;</code>
       */
      public double getMaxSpeed() {
        return maxSpeed_;
      }
      /**
       * <code>optional double maxSpeed = 1;</code>
       */
      public Builder setMaxSpeed(double value) {
        bitField0_ |= 0x00000001;
        maxSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double maxSpeed = 1;</code>
       */
      public Builder clearMaxSpeed() {
        bitField0_ = (bitField0_ & ~0x00000001);
        maxSpeed_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:amber.drive_to_point_proto.Configuration)
    }

    static {
      defaultInstance = new Configuration(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:amber.drive_to_point_proto.Configuration)
  }

  public static final int SETTARGETS_FIELD_NUMBER = 80;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      java.lang.Boolean> setTargets = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GETNEXTTARGET_FIELD_NUMBER = 81;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      java.lang.Boolean> getNextTarget = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GETNEXTTARGETS_FIELD_NUMBER = 82;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      java.lang.Boolean> getNextTargets = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GETVISITEDTARGET_FIELD_NUMBER = 83;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      java.lang.Boolean> getVisitedTarget = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GETVISITEDTARGETS_FIELD_NUMBER = 84;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      java.lang.Boolean> getVisitedTargets = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int TARGETS_FIELD_NUMBER = 85;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets> targets = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets.class,
        pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Targets.getDefaultInstance());
  public static final int LOCATION_FIELD_NUMBER = 86;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location> location = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location.class,
        pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Location.getDefaultInstance());
  public static final int GETCONFIGURATION_FIELD_NUMBER = 87;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      java.lang.Boolean> getConfiguration = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int CONFIGURATION_FIELD_NUMBER = 88;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration> configuration = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration.class,
        pl.edu.agh.amber.drivetopoint.proto.DriveToPointProto.Configuration.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_drive_to_point_proto_Targets_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_drive_to_point_proto_Targets_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_drive_to_point_proto_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_drive_to_point_proto_Location_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_drive_to_point_proto_Configuration_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_drive_to_point_proto_Configuration_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024drive_to_point.proto\022\032amber.drive_to_p" +
      "oint_proto\032\017drivermsg.proto\"N\n\007Targets\022\026" +
      "\n\nlongitudes\030\001 \003(\001B\002\020\001\022\025\n\tlatitudes\030\002 \003(" +
      "\001B\002\020\001\022\024\n\010radiuses\030\003 \003(\001B\002\020\001\"L\n\010Location\022" +
      "\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\022\t\n\001p\030\003 \001(\001\022\014\n\004alfa" +
      "\030\004 \001(\001\022\021\n\ttimeStamp\030\005 \001(\003\"!\n\rConfigurati" +
      "on\022\020\n\010maxSpeed\030\001 \001(\001:$\n\nsetTargets\022\020.amb" +
      "er.DriverMsg\030P \001(\010:\'\n\rgetNextTarget\022\020.am" +
      "ber.DriverMsg\030Q \001(\010:(\n\016getNextTargets\022\020." +
      "amber.DriverMsg\030R \001(\010:*\n\020getVisitedTarge",
      "t\022\020.amber.DriverMsg\030S \001(\010:+\n\021getVisitedT" +
      "argets\022\020.amber.DriverMsg\030T \001(\010:F\n\007target" +
      "s\022\020.amber.DriverMsg\030U \001(\0132#.amber.drive_" +
      "to_point_proto.Targets:H\n\010location\022\020.amb" +
      "er.DriverMsg\030V \001(\0132$.amber.drive_to_poin" +
      "t_proto.Location:*\n\020getConfiguration\022\020.a" +
      "mber.DriverMsg\030W \001(\010:R\n\rconfiguration\022\020." +
      "amber.DriverMsg\030X \001(\0132).amber.drive_to_p" +
      "oint_proto.ConfigurationB8\n#pl.edu.agh.a" +
      "mber.drivetopoint.protoB\021DriveToPointPro",
      "to"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_amber_drive_to_point_proto_Targets_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_amber_drive_to_point_proto_Targets_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_amber_drive_to_point_proto_Targets_descriptor,
              new java.lang.String[] { "Longitudes", "Latitudes", "Radiuses", });
          internal_static_amber_drive_to_point_proto_Location_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_amber_drive_to_point_proto_Location_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_amber_drive_to_point_proto_Location_descriptor,
              new java.lang.String[] { "X", "Y", "P", "Alfa", "TimeStamp", });
          internal_static_amber_drive_to_point_proto_Configuration_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_amber_drive_to_point_proto_Configuration_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_amber_drive_to_point_proto_Configuration_descriptor,
              new java.lang.String[] { "MaxSpeed", });
          setTargets.internalInit(descriptor.getExtensions().get(0));
          getNextTarget.internalInit(descriptor.getExtensions().get(1));
          getNextTargets.internalInit(descriptor.getExtensions().get(2));
          getVisitedTarget.internalInit(descriptor.getExtensions().get(3));
          getVisitedTargets.internalInit(descriptor.getExtensions().get(4));
          targets.internalInit(descriptor.getExtensions().get(5));
          location.internalInit(descriptor.getExtensions().get(6));
          getConfiguration.internalInit(descriptor.getExtensions().get(7));
          configuration.internalInit(descriptor.getExtensions().get(8));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pl.edu.agh.amber.common.proto.CommonProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
