// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: location.proto

package pl.edu.agh.amber.location.proto;

public final class LocationProto {
  private LocationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(pl.edu.agh.amber.location.proto.LocationProto.getLocation);
    registry.add(pl.edu.agh.amber.location.proto.LocationProto.currentLocation);
    registry.add(pl.edu.agh.amber.location.proto.LocationProto.uploadMap);
  }
  public interface LocationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional double x = 1;
    /**
     * <code>optional double x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>optional double x = 1;</code>
     */
    double getX();

    // optional double y = 2;
    /**
     * <code>optional double y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>optional double y = 2;</code>
     */
    double getY();

    // optional double p = 3;
    /**
     * <code>optional double p = 3;</code>
     */
    boolean hasP();
    /**
     * <code>optional double p = 3;</code>
     */
    double getP();

    // optional double alfa = 4;
    /**
     * <code>optional double alfa = 4;</code>
     */
    boolean hasAlfa();
    /**
     * <code>optional double alfa = 4;</code>
     */
    double getAlfa();

    // optional int64 timeStamp = 5;
    /**
     * <code>optional int64 timeStamp = 5;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>optional int64 timeStamp = 5;</code>
     */
    long getTimeStamp();
  }
  /**
   * Protobuf type {@code amber.location_proto.Location}
   */
  public static final class Location extends
      com.google.protobuf.GeneratedMessage
      implements LocationOrBuilder {
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Location(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Location defaultInstance;
    public static Location getDefaultInstance() {
      return defaultInstance;
    }

    public Location getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              x_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              y_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              p_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              alfa_ = input.readDouble();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timeStamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.agh.amber.location.proto.LocationProto.internal_static_amber_location_proto_Location_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.agh.amber.location.proto.LocationProto.internal_static_amber_location_proto_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.edu.agh.amber.location.proto.LocationProto.Location.class, pl.edu.agh.amber.location.proto.LocationProto.Location.Builder.class);
    }

    public static com.google.protobuf.Parser<Location> PARSER =
        new com.google.protobuf.AbstractParser<Location>() {
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Location(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional double x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private double x_;
    /**
     * <code>optional double x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double x = 1;</code>
     */
    public double getX() {
      return x_;
    }

    // optional double y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private double y_;
    /**
     * <code>optional double y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double y = 2;</code>
     */
    public double getY() {
      return y_;
    }

    // optional double p = 3;
    public static final int P_FIELD_NUMBER = 3;
    private double p_;
    /**
     * <code>optional double p = 3;</code>
     */
    public boolean hasP() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double p = 3;</code>
     */
    public double getP() {
      return p_;
    }

    // optional double alfa = 4;
    public static final int ALFA_FIELD_NUMBER = 4;
    private double alfa_;
    /**
     * <code>optional double alfa = 4;</code>
     */
    public boolean hasAlfa() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double alfa = 4;</code>
     */
    public double getAlfa() {
      return alfa_;
    }

    // optional int64 timeStamp = 5;
    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timeStamp_;
    /**
     * <code>optional int64 timeStamp = 5;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 timeStamp = 5;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    private void initFields() {
      x_ = 0D;
      y_ = 0D;
      p_ = 0D;
      alfa_ = 0D;
      timeStamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, p_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, alfa_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, timeStamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, p_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, alfa_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timeStamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pl.edu.agh.amber.location.proto.LocationProto.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.location.proto.LocationProto.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.location.proto.LocationProto.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.location.proto.LocationProto.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.location.proto.LocationProto.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.location.proto.LocationProto.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.location.proto.LocationProto.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pl.edu.agh.amber.location.proto.LocationProto.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.location.proto.LocationProto.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.location.proto.LocationProto.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.agh.amber.location.proto.LocationProto.Location prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code amber.location_proto.Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.edu.agh.amber.location.proto.LocationProto.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.agh.amber.location.proto.LocationProto.internal_static_amber_location_proto_Location_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.agh.amber.location.proto.LocationProto.internal_static_amber_location_proto_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.edu.agh.amber.location.proto.LocationProto.Location.class, pl.edu.agh.amber.location.proto.LocationProto.Location.Builder.class);
      }

      // Construct using pl.edu.agh.amber.location.proto.LocationProto.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        p_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        alfa_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        timeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.agh.amber.location.proto.LocationProto.internal_static_amber_location_proto_Location_descriptor;
      }

      public pl.edu.agh.amber.location.proto.LocationProto.Location getDefaultInstanceForType() {
        return pl.edu.agh.amber.location.proto.LocationProto.Location.getDefaultInstance();
      }

      public pl.edu.agh.amber.location.proto.LocationProto.Location build() {
        pl.edu.agh.amber.location.proto.LocationProto.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.edu.agh.amber.location.proto.LocationProto.Location buildPartial() {
        pl.edu.agh.amber.location.proto.LocationProto.Location result = new pl.edu.agh.amber.location.proto.LocationProto.Location(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.p_ = p_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.alfa_ = alfa_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timeStamp_ = timeStamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.agh.amber.location.proto.LocationProto.Location) {
          return mergeFrom((pl.edu.agh.amber.location.proto.LocationProto.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.edu.agh.amber.location.proto.LocationProto.Location other) {
        if (other == pl.edu.agh.amber.location.proto.LocationProto.Location.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasP()) {
          setP(other.getP());
        }
        if (other.hasAlfa()) {
          setAlfa(other.getAlfa());
        }
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.edu.agh.amber.location.proto.LocationProto.Location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.edu.agh.amber.location.proto.LocationProto.Location) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional double x = 1;
      private double x_ ;
      /**
       * <code>optional double x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double x = 1;</code>
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>optional double x = 1;</code>
       */
      public Builder setX(double value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        onChanged();
        return this;
      }

      // optional double y = 2;
      private double y_ ;
      /**
       * <code>optional double y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double y = 2;</code>
       */
      public double getY() {
        return y_;
      }
      /**
       * <code>optional double y = 2;</code>
       */
      public Builder setY(double value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        onChanged();
        return this;
      }

      // optional double p = 3;
      private double p_ ;
      /**
       * <code>optional double p = 3;</code>
       */
      public boolean hasP() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double p = 3;</code>
       */
      public double getP() {
        return p_;
      }
      /**
       * <code>optional double p = 3;</code>
       */
      public Builder setP(double value) {
        bitField0_ |= 0x00000004;
        p_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double p = 3;</code>
       */
      public Builder clearP() {
        bitField0_ = (bitField0_ & ~0x00000004);
        p_ = 0D;
        onChanged();
        return this;
      }

      // optional double alfa = 4;
      private double alfa_ ;
      /**
       * <code>optional double alfa = 4;</code>
       */
      public boolean hasAlfa() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double alfa = 4;</code>
       */
      public double getAlfa() {
        return alfa_;
      }
      /**
       * <code>optional double alfa = 4;</code>
       */
      public Builder setAlfa(double value) {
        bitField0_ |= 0x00000008;
        alfa_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double alfa = 4;</code>
       */
      public Builder clearAlfa() {
        bitField0_ = (bitField0_ & ~0x00000008);
        alfa_ = 0D;
        onChanged();
        return this;
      }

      // optional int64 timeStamp = 5;
      private long timeStamp_ ;
      /**
       * <code>optional int64 timeStamp = 5;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 timeStamp = 5;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>optional int64 timeStamp = 5;</code>
       */
      public Builder setTimeStamp(long value) {
        bitField0_ |= 0x00000010;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timeStamp = 5;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:amber.location_proto.Location)
    }

    static {
      defaultInstance = new Location(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:amber.location_proto.Location)
  }

  public static final int GET_LOCATION_FIELD_NUMBER = 60;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      java.lang.Boolean> getLocation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int CURRENTLOCATION_FIELD_NUMBER = 61;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      pl.edu.agh.amber.location.proto.LocationProto.Location> currentLocation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        pl.edu.agh.amber.location.proto.LocationProto.Location.class,
        pl.edu.agh.amber.location.proto.LocationProto.Location.getDefaultInstance());
  public static final int UPLOAD_MAP_FIELD_NUMBER = 62;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      java.lang.String> uploadMap = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_location_proto_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_location_proto_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016location.proto\022\024amber.location_proto\032\017" +
      "drivermsg.proto\"L\n\010Location\022\t\n\001x\030\001 \001(\001\022\t" +
      "\n\001y\030\002 \001(\001\022\t\n\001p\030\003 \001(\001\022\014\n\004alfa\030\004 \001(\001\022\021\n\tti" +
      "meStamp\030\005 \001(\003:&\n\014get_location\022\020.amber.Dr" +
      "iverMsg\030< \001(\010:I\n\017currentLocation\022\020.amber" +
      ".DriverMsg\030= \001(\0132\036.amber.location_proto." +
      "Location:$\n\nupload_map\022\020.amber.DriverMsg" +
      "\030> \001(\tB0\n\037pl.edu.agh.amber.location.prot" +
      "oB\rLocationProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_amber_location_proto_Location_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_amber_location_proto_Location_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_amber_location_proto_Location_descriptor,
              new java.lang.String[] { "X", "Y", "P", "Alfa", "TimeStamp", });
          getLocation.internalInit(descriptor.getExtensions().get(0));
          currentLocation.internalInit(descriptor.getExtensions().get(1));
          uploadMap.internalInit(descriptor.getExtensions().get(2));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pl.edu.agh.amber.common.proto.CommonProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
